spring:
  application:
    name: spring-boot-and-data-jpa

  datasource:
    url: jdbc:mysql://localhost:3306/e_learning_platform_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 18ak1a05c2
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
